---
title: "Digitally native methodology to quantify greenhouse gas emission reductions from improved wood-fuelled cookstoves"
author: "Nova Institute"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: 
    fig_caption: yes
    number_sections: yes
  html_document: default
  word_document: default
subtitle: Simulation of a 1000-household project
header-includes: \usepackage{longtable} \usepackage{float} \usepackage{subfig} \usepackage{booktabs}
  \usepackage{multirow} \usepackage{tabu} \floatplacement{table}{H} \floatplacement{figure}{H}
  \usepackage{caption}
  \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- P01.05	Map reporting indicators
P01.05.01	Finalise list of indicators
P01.05.02	Detail specification for each
P01.05.03	Definition, rationale, Credibility,  calculation (Formula, UoM) -->


```{=tex}
\clearpage
\pagenumbering{roman}
\tableofcontents
\newpage
\pagenumbering{arabic}
```

# CO~2~ emission reduction due to project activity (t/yr)  

**Definition**  

The total mass of CO~2~ avoided per annum due to the project activity.

**Rationale**  

CO~2~ emissions are linked to climate change. 

**Source(s) of data**  

*  stove tests (WBT)
*  baseline and project field tests (KT)
*  non-renewable biomass (NRB) assessment
*  (ongoing) stove usage monitoring
*  stove use logbooks
*  usage survey

**Credibility** 

*Avoidance of specification error*  
Give preference to tests that represent the actual situation of the end-user.   
Give preference to objective methods for ongoing sampling.  
Use a randomly selected sample.

*Avoidance of coverage or frame error*  
Keep a complete record of all participating households.

*Avoidance of non-response error*  
Consider a moderate compensation to households for participating in tests that are invasive (like the KPT).

*Avoidance of measurement error*  
Give preference to objective measurements.  
Use triangulation.

*Avoidance of processing errors*  
Report calculations transparently so that all processing steps, including intermediate steps, are visible.

**Calculation** 

## Notation


$fr_{(B)ijk}$: fire frequency for household *j* in subpopulation *i* on day *k* in the baseline scenario of the KT phase.

$fr_{(P)ijk}$: fire frequency for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$fr_{(BS)ijk}$: Brick Star frequency for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$fr^*_{(BS)ijk}$: fire frequency for Brick Star for household *j* in subpopulation *i* on day *k* in the post KT phase.

$x_{(B)ijk}$: daily fuel use (in kg) for household *j* in subpopulation *i* on day *k* in the baseline scenario of the KT phase.

$x_{(P)ijk}$: daily fuel use (in kg) for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$x_{(BS)ijk}$: daily Brick Star fuel use (in kg) for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$n_{(B)ij}$: total number of days that household *j* in subpopulation *i* was observed in the baseline scenario of the KT phase.

$n_{(P)ij}$: total number of days that household *j* in subpopulation *i* was observed in the project scenario of the KT phase.

$n^*_{ij}$: total number of days that household *j* in subpopulation *i* was observed in the post KT phase.

$n_{i}$: total number of subpopulations in the project.

## Calculation of $\bm{ER_y}$

#### Calculation

$$ER_{y} = BE_{y}- PE_{y}-LE_{y}$$

Where:  

$ER_{y} =$ The total mass of CO~2~ avoided in year *y* across all project participants due to the project activity (tonnes)  
$BE_{y} =$ The total baseline CO~2~ emissions for year *y* across all project participants (tonnes)  
$PE_{y} =$ The total project CO~2~ emissions for year *y* across all project participants (tonnes)
$LE_{y} =$ The total leakage CO~2~ emissions for year *y* across all project participants (tonnes)

#### Presentation and simulation results

## Calculation of project CO~2~ emissions 

### Calculation of $\bm{PE_y}$

#### Calculation

$PE_{y}$ is calculated as:

$$PE_{y} = \sum_{f} C_{(P)y,f} \times EF_{(CO_2)f} \times f_{(NRB)y}$$ 

Where:  

$C_{(P)y,f} =$ The total project consumption of fuel *f* for year *y* across all project participants (tonnes)  
$EF_{(CO_2)f} =$ CO~2~ emission factor for fuel *f*  
$f_{(NRB)y} =$ The fraction of non-renewable biomass in the fuel-sourcing environment for year *y* 

For simplicity in notation we will from this point forth use the notation $C_{(P)}$ for $C_{(P)y,f}$ with the understanding that $C_{(P)}$ is the total fuel consumption across all subpopulations and households for year *y* and fuel type *f*. 

#### Presentation and simulation results

### Calculation of $\bm{C_{(P)}}$

#### Calculation

$C_{(P)}$ is calculated as:  

$$C_{(P)} = 
\sum_{i}^{n_i} C_{(P)i}$$

and $C_{(P)i}$ is the total fuel consumption in the project scenario for subpopulation *i*.

#### Presentation and simulation results

### Calculation of $\bm{C_{(P)i}}$ 

#### Calculation

$C_{(P)i}$ is calculated as 


$$C_{(P)i}=(\overline{d}_{(P)i} \times N_{(P)i}) \times (\overline{fr^*}_{(BS)i} \times \overline{x}_{(BS)i})$$

*   $\overline{d}_{(P)i}$ is the average days of project operatian in subpopulation *i*.
*   $N_{(P)i}$ is the project population size in subpopulation *i*.
*   $\overline {fr^*}_{(BS)i}$ is the average Brick Star frequency per day in subpopulation *i* in the post KT phase .
*   $\overline{x}_{(BS)i}$ is the average Brick Star fuel use (in kg) for subpopulation *i* in the project scenario of the KT phase.

#### Presentation and simulation results


### Calculation of $\bm{d_{ij}}$

#### Calculation

The average days of project operation is calculated as 
$$ \overline{d}_{i}=\frac{1}{n_{i}}\sum d_{ij}$$
and $d_{ij}$ is the total days of project operation for household *j* in subpopulation *i*. The total days of operation for each household can be determined as the number of days since the project technology has been implemented for each household and will be available in the project register.

#### Presentation and simulation results

### Calculation of $\bm{\overline{fr^*}_{(BS)i}}$

#### Calculation

The average Brick Star frequency per day $\overline{fr^*}_{(BS)i}$ for subpopulation *i* is determined from a sample in the post KT phase and is calculated as
$$\overline{fr^*}_{(BS)i}=\frac{1}{n^*_i} \sum_i^{n^*_i}\frac{fr^*_{(BS)ij.}}{n^*_{ij}}$$

*   $fr^*_{(BS)ij.}$ is the total frequency Brick Star fires for household *j* in subpopulation *i* for the post KT phase.

*   $n^*_{ij}$ is the total number of days that household *j* in subpopulation *i* was observed in the post KT phase.

* $n^*_i$ is the number of households that were observed in the post KT phase.


#### Presentation and simulation results

### Calculation of $\bm{\overline{x}_{(BS)i}}$

#### Calculation

The average Brick Star fuel use (in kg) in the project scenario for subpopulation *i* is calculated as the average of the household average fuel use per Brick Star fire.  $$\overline{x}_{(BS)i}=\frac{1}{n_{(P)i}}\sum_{j}^{n_{i}} \frac{x_{(BS)ij.}}{fr_{(BS)ij.}}$$


#### Presentation and simulation results

### Calculation of $\bm{x_{(BS)ij.}}$

#### Calculation

The total Brick Star fuel use for household *j* in subpopulation *i* is the total fuel use in the project scenario minus the fuel use by non-Brick Star fires in the project scenario.

$$x_{(BS)ij.}=x_{(P)ij.}-(\overline{x}_{(B)i} \times (fr_{(P)ij.}-fr_{(BS)ij.}))$$
#### Presentation and simulation results

## Calculation of baseline CO~2~ emissions

### Calculation of $\bm{BE_y}$ 

#### Calculation 

$BE_{y}$ is calculated as:

$$BE_{y} = \sum_{f} C_{(B)y,f} \times EF_{(CO_2)f} \times f_{(NRB)y}$$ 

Where:  

$C_{(B)y,f} =$ The total baseline consumption of fuel *f* for year *y* across all project participants (tonnes)  
$EF_{(CO_2)f} =$ CO~2~ emission factor for fuel *f*  
$f_{(NRB)y} =$ The fraction of non-renewable biomass in the fuel-sourcing environment for year *y*   

For simplicity in notation we will from this point forth use the notation $C_{(B)}$ for $C_{(B)y,f}$ with the understanding that $C_{(B)}$ is the total fuel consumption across all subpopulations and households for year *y* and fuel type *f*. 

#### Presentation and simulation results

### Calculation of $\bm{C_{(B)}}$

#### Calculation 

$C_{(B)}$ is calculated as:

$$C_{(B)} = \sum_{i}^{n_i} eef_{i} \times C_{(P)i}$$

$C_{(P)i}$ is the total fuel consumption for subpopulations *i* (see calculation in previous paragraph).

$eef_i$ is the energy efficiency factor for subpopulation *i*.

#### Presentation and simulation results

### Calculation of $\bm{eef_i}$

#### Calculation

$eef_i$ is calculated as

$$eef_i = \frac{\overline{x}_{(B)i}\times \overline{rr}_i}{\overline{x}_{(BS
)i}}$$

Where: 
$\overline{x}_{(B)i}$ the average fuel use (in kg) in the baseline scenario for subpopulation *i*.

$\overline{rr}_i$ the average replacement ratio at which non-Brick Star fires are replaced by Brick Star fires for subpopulation *i*.

$\overline{x}_{(BS)i}$ the average Brick Star fuel use (in kg) in the baseline scenario for subpopulation *i*.

#### Presentation and simulation results

### Calculation of $\bm{\overline{x}_{(B)i}}$

#### Calculation
 
The average fuel use (in kg) in the baseline scenario for subpopulation *i* is calculated as the average fuel use (in kg) for the *j* households in subpopulation *i*.

$$\overline{x}_{(B)i}= \frac{1}{n_{ij}}\sum_{j} \overline{x}_{(B)ij}$$
and $\overline{x}_{(B)ij}$ is the average fuel use (in kg) in the baseline scenario for household *j* subpopulation *i*. $$\overline{x}_{(B)ij}=\frac{1}{n_{ijk}}\sum_{k}^{n_{ijk}} {x}_{(B)ijk}$$

#### Presentation and simulation results

### Calculation of $\bm{\overline{rr}_{i}}$

#### Calculation

The average replacement ratio is the average ratio for subpopulation *i* of the replaced non-Brick Star fires replaced by Brick Star fires and is calculated as

$$\overline{rr}_{i} = \frac{1}{n_{ij}}\sum_{j} rr_{ij}$$
and $rr_{ij}$ is the replacement ratio for household *j* in subpopulation *i*.

#### Presentation and simulation results

### Calculation $\bm{rr_{ij}}$

#### Calculation

$$rr_{ij} = \frac{\overline{fr}_{(B)ij} - (\overline{fr}_{(P)ij}-\overline{fr}_{(BS)ij})}{\overline{fr}_{(BS)ij}}$$
$\overline{fr}_{(B)ij}$ is the average number of fires per day in the baseline scenario for household *j* in subpopulation *i* and is calculated as the total fires in the baseline scenario for household *j* in subpopulation *i* divided by the total days for household *j* in subpopulation *i* in the baseline scenario.

#### Presentation and simulation results

### Calculation of $\bm{\overline{fr}_{(B)ij}}$

#### Calculation

$$\overline{fr}_{(B)ij} = \frac{fr_{(B)ij.}}{{n_{(B)ij}}}$$
Similarly $\overline{fr}_{(P)}ij$ is the average number of fires per day in the project scenario for household *j* in subpopulation *i* $$\overline{fr}_{(P)ij} = \frac{fr_{(P)ij.}}{{n_{(P)ij}}}$$ and $\overline{fr}_{(BS)ij}$ is the average number of Brick Star fires per day in the project scenario for household *j* in subpopulation *i* $$\overline{fr}_{(BS)ij} = \frac{fr_{(BS)ij.}}{{n_{(BS)ij}}}$$ 

#### Presentation and simulation results

## Calculation of leakage CO~2~ emissions

### Calculation of $\bm{LE_y}$ 

#### Calculation

Leakage will be due to continued use of baseline technology.
$LE_{y}$ is calculated as:

$$LE_{y} = \sum_{f} L_{(P)y,f} \times EF_{(CO_2)f} \times f_{(NRB)y}$$ 

Where:  

$L_{(P)y,f} =$ The total baseline consumption of fuel *f* for year *y* across all project participants (tonnes)  
$EF_{(CO_2)f} =$ CO~2~ emission factor for fuel *f*  
$f_{(NRB)y} =$ The fraction of non-renewable biomass in the fuel-sourcing environment for year *y*   

For simplicity in notation we will from this point forth use the notation $L_{(P)}$ for $L_{(P)y,f}
$ with the understanding that $L_{}$ is the total fuel consumption across all subpopulations and households for year *y* and fuel type *f*. 

### Calculation or $\bm{L_{(P)}}$

#### Calculation

$L_{(P)}$ is calculated as:

$$L_{(P)} = \sum_{i}^{n_i}  L_{(P)i}$$
and $L_{(P)i}$ is the total leakage in the project scenario for subpopulation *i*.

### Calculation of $\bm{L_{(P)i}}$ 

$L_{(P)i}$ is calculated as 

$$L_{(P)i}=(\overline{d}_{(P)i} \times N_{(P)i}) \times (
\overline{frr}_i\times \overline{fr^*}_{(BS)i} \times \overline{x}_{(B)i})$$

*   $\overline{d}_{(P)i}$ is the average days of project operation in subpopulation *i*.
*   $N_{(P)i}$ is the project population size in subpopulation *i*.
*   $\overline{frr}_i$ is the average frequency ratio of non Brick Star fires to the Brick Star fires in subpopulation *i* in the project scenario of the KT phase.
*   $\overline {fr^*}_{(BS)i}$ is the average Brick Star frequency per day in subpopulation *i* in the post KT phase .
*   $\overline{x}_{(B)i}$ is the average fuel use (in kg) for subpopulation *i* in the baseline scenario of the KT phase.

### Calculation of $\bm{\overline{frr}_i }$

The average frequency ratio of non-Brick Star fires to the Brick Star fires in the project scenario for household *j* in subpopulation *i* is calculated as $$\overline{frr}_i = \frac {1}{n_{(P)i}} \sum_{j}\frac{fr_{(P)ij.}-fr_{(BS)ij.}}{fr_{(BS)ij.}}$$


