---
title: "Digitally native methodology to quantify greenhouse gas emission reductions from improved wood-fuelled cookstoves"
author: "Nova Institute"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: 
    fig_caption: yes
    number_sections: yes
  html_document: default
  word_document: default
subtitle: Impacted environments (P01.04) and reporting indicators (P01.05)
header-includes: \usepackage{longtable} \usepackage{float} \usepackage{subfig} \usepackage{booktabs}
  \usepackage{multirow} \usepackage{tabu} \floatplacement{table}{H} \floatplacement{figure}{H}
  \usepackage{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- P01.05	Map reporting indicators
P01.05.01	Finalise list of indicators
P01.05.02	Detail specification for each
P01.05.03	Definition, rationale, Credibility,  calculation (Formula, UoM) -->


```{=tex}
\clearpage
\pagenumbering{roman}
\tableofcontents
\newpage
\pagenumbering{arabic}
```

# Environments

Five environments are potentially impacted by the project activity:

*  household members
*  ambient atmosphere
*  indoor atmosphere
*  fuel-sourcing environment
*  implementation settlement

## Environment parameters: household members

Three parameters of *household members* are relevant:

*  wood collection effort
*  wood collection cost
*  health risk to household members

## Environment parameters: ambient atmosphere  

The following parameters of *ambient atmosphere* are relevant:

* concentration of CO~2~ 
* concentration of particulate matter (PM) 
* concentration of SO~2~ 
* concentration of black carbon (BC)  


## Environment parameters: indoor atmosphere

Two parameters of the *indoor atmosphere* are relevant:

*  concentration of CO
*  concentration of PM

## Environment parameters: fuel-sourcing environment

The following parameters of the *fuel-sourcing environment* are relevant:  

*  location
*  woody biomass density
*  species composition

## Environment parameters: implementation settlement

The following parameters of the *implementation settlement* are relevant:

*  location
*  population
   -  number of persons
   -  number of households
   -  population density
*  prevalence of household wood use
*  amount of wood used per regular wood-using household for each technology type
*  presence of similar projects



# Indicators 




## Indicators: household members

The state of *household members* will be expressed using the following indicators:

1. Time spent on wood collection (person.hours).
2. Expenditure on fuelwood (Rand/yr).




### \label{timecollect}Time spent on wood collection (person.hours) 

**Definition**  

Total annual duration of wood collection activity across all participating households.

**Rationale**  

Collection of wood is time-consuming and hard work, often done by women and girls, and exposes them to risks of violence when they have to access isolated areas. 

**Source(s) of data** 

In order of precision:

1. GPS tracking of a randomly selected sample of wood collectors.
2. Logbooks kept by a randomly selected sample of wood collectors.
3. Post-hoc interviews with a randomly selected sample of wood collectors.

**Credibility**  

*Avoidance of specification error*  
It is easy for households to understand the concept of time spent on wood collection, so the risk of specification error is small. Care should, however, be taken where wood collectors combine wood collection with other activities. 

*Avoidance of coverage or frame error*  
Fully document all participants.

*Avoidance of non-response error*  
Use a documented sampling strategy.  
MCAR: Sample additional respondents above the minimum required.  
MAR: Analyse correlation between outcomes and population variables. If high correlations exist, consider a sampling strategy (e.g. stratified sampling) that ensures proper representation of subgroups in danger of under-representation.   
MNAR: Where people who spend more time collecting wood cannot be monitored exactly because of the time spent on collecting wood, results may be biased. Where needed, use multiple methods (including, if need be, lower-accuracy methods) to monitor all sampled respondents.  

*Avoidance of measurement error*  
Use triangulation of methods.  
Give priority to objective, higher-accuracy methods (see *Source(s) of data*).

*Avoidance of processing errors*  
Expose intermediate calculation steps in reporting.  
Compare multiple calculation approaches.

**Calculation**  

$$T_{wood} = \bar t \times 52 \times N_{hh} $$ 

Where:

$T_{wood} =$ Total amount of time spent on wood collection by participating households per year (person.hours)  
$\bar t =$ Mean duration of time spent per household per week on wood collection (hours)    
$N_{hh} =$ Number of households participating in the project activity  

**Unit of measure**  

person.hours





### Expenditure on fuelwood (Rand/yr)  

**Definition**  

Total annual expenditure on fuelwood across all participating households.

**Rationale**  

Low-income households spend substantial proportions of their income on energy. There are geographic areas where wood availability has decreased to such an extent that harvesting wood on foot is not practical. 

**Source(s) of data**  

In order of precision:  

1. Household wood fuel expenditure logbooks kept by a randomly selected sample of wood collectors. 
2. Post-hoc household interviews with a randomly selected sample of wood collectors.  

**Credibility** 

*Avoidance of specification error*  
Expenditure is an easy-to-understand concept, so the risk for specification error is small.

*Avoidance of coverage or frame error*  
Fully document all participants.

*Avoidance of non-response error*  
Use a documented sampling strategy .

MCAR: Sample additional respondents above the minimum required.  
MAR: Analyse correlation between outcomes and population variables. If high correlations exist, consider a sampling strategy (e.g. stratified sampling) that ensures proper representation of subgroups in danger of under-representation.  
MNAR: Where people who spend more money on wood cannot be effectively monitored exactly because of the higher expenditure on wood, results may be biased. Where needed, use multiple methods (including, if need be, lower-accuracy methods) to monitor all sampled respondents.

*Avoidance of measurement error*  
Use triangulation.
Give preference to higher-accuracy methods.

*Avoidance of processing errors*  
Expose intermediate calculation steps in reporting.  
Compare multiple calculation approaches were possible.

**Calculation** 

$$ R_{wood} = \bar r \times 52 \times N_{hh} $$ 

Where:

$R_{wood} =$ Total annual expenditure on fuelwood across all participating households (R/yr)  
$\bar r =$ Mean expenditure on fuelwood per household per week (R/w)  
$N_{hh} =$ Number of households participating in the project activity

**Unit of measure**  
Rand/yr






## Indicators: ambient atmosphere  

The state of the *ambient atmosphere* will be expressed using the following indicators:

1. CO~2~ emission reduction due to project activity (t/yr).
2. PM~10~ emission reduction due to project activity (t/yr).
3. SO~2~ emission reduction due to project activity (t/yr).




### CO~2~ emission reduction due to project activity (t/yr)  

**Definition**  

The total mass of CO~2~ avoided per annum due to the project activity.

**Rationale**  

CO~2~ emissions are linked to climate change. 

**Source(s) of data**  

*  stove tests (WBT)
*  baseline and project field tests (KT)
*  non-renewable biomass (NRB) assessment
*  (ongoing) stove usage monitoring
*  stove use logbooks
*  usage survey

**Credibility** 

*Avoidance of specification error*  
Give preference to tests that represent the actual situation of the end-user.   
Give preference to objective methods for ongoing sampling.  
Use a randomly selected sample.

*Avoidance of coverage or frame error*  
Keep a complete record of all participating households.

*Avoidance of non-response error*  
Consider a moderate compensation to households for participating in tests that are invasive (like the KPT).

*Avoidance of measurement error*  
Give preference to objective measurements.  
Use triangulation.

*Avoidance of processing errors*  
Report calculations transparently so that all processing steps, including intermediate steps, are visible.

**Calculation** 

### Notation


$fr_{(B)ijk}$: fire frequency for household *j* in subpopulation *i* on day *k* in the baseline scenario of the KT phase.

$fr_{(P)ijk}$: fire frequency for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$fr_{(BS)ijk}$: Brick Star frequency for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$fr^*_{(BS)ijk}$: fire frequency for Brick Star for household *j* in subpopulation *i* on day *k* in the post KT phase.

$x_{(B)ijk}$: daily fuel use (in kg) for household *j* in subpopulation *i* on day *k* in the baseline scenario of the KT phase.

$x_{(P)ijk}$: daily fuel use (in kg) for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$x_{(BS)ijk}$: daily Brick Star fuel use (in kg) for household *j* in subpopulation *i* on day *k* in the project scenario of the KT phase.

$n_{(B)ij}$: total number of days that household *j* in subpopulation *i* was observed in the baseline scenario of the KT phase.

$n_{(P)ij}$: total number of days that household *j* in subpopulation *i* was observed in the project scenario of the KT phase.

$n^*_{ij}$: total number of days that household *j* in subpopulation *i* was observed in the post KT phase.

$n_{i}$: total number of subpopulations in the project.

### Main Formula


$$ER_{y} = BE_{y}- PE_{y}-LE_{y}$$

Where:  

$ER_{y} =$ The total mass of CO~2~ avoided in year *y* across all project participants due to the project activity (tonnes)  
$BE_{y} =$ The total baseline CO~2~ emissions for year *y* across all project participants (tonnes)  
$PE_{y} =$ The total project CO~2~ emissions for year *y* across all project participants (tonnes)
$LE_{y} =$ The total leakage CO~2~ emissions for year *y* across all project participants (tonnes)

### Calculation of project CO~2~ emissions 

$PE_{y}$ is calculated as:

$$PE_{y} = \sum_{f} C_{(P)y,f} \times EF_{(CO_2)f} \times f_{(NRB)y}$$ 

Where:  

$C_{(P)y,f} =$ The total project consumption of fuel *f* for year *y* across all project participants (tonnes)  
$EF_{(CO_2)f} =$ CO~2~ emission factor for fuel *f*  
$f_{(NRB)y} =$ The fraction of non-renewable biomass in the fuel-sourcing environment for year *y* (as calculated in section \ref{sec:ifse})  

For simplicity in notation we will from this point forth use the notation $C_{(P)}$ for $C_{(P)y,f}$ with the understanding that $C_{(P)}$ is the total fuel consumption across all subpopulations and households for year *y* and fuel type *f*. 

$C_{(P)}$ is calculated as:  

$$C_{(P)} = 
\sum_{i}^{n_i} C_{(P)i}$$

and $C_{(P)i}$ is the total fuel consumption in the project scenario for subpopulation *i*.
$C_{(P)i}$ is calculated as 


$$C_{(P)i}=(\overline{d}_{(P)i} \times N_{(P)i}) \times (\overline{fr^*}_{(BS)i} \times \overline{x}_{(BS)i})$$

*   $\overline{d}_{(P)i}$ is the average days of project operatian in subpopulation *i*.
*   $N_{(P)i}$ is the project population size in subpopulation *i*.
*   $\overline {fr^*}_{(BS)i}$ is the average Brick Star frequency per day in subpopulation *i* in the post KT phase .
*   $\overline{x}_{(BS)i}$ is the average Brick Star fuel use (in kg) for subpopulation *i* in the project scenario of the KT phase.

***

The average days of project operation is calculated as 
$$ \overline{d}_{i}=\frac{1}{n_{i}}\sum d_{ij}$$
and $d_{ij}$is the total days of project operation for household *j* in subpopulation *i*. The total days of operation for each household can be determined as the number of days since the project technology has been implemented for each household and will be available in the project register.


****

The average Brick Star frequency per day $\overline{fr^*}_{(BS)i}$ for subpopulation *i* is determined from a sample in the post KT phase and is calculated as
$$\overline{fr^*}_{(BS)i}=\frac{1}{n^*_i} \sum_i^{n^*_i}\frac{fr^*_{(BS)ij.}}{n^*_{ij}}$$

*   $fr^*_{(BS)ij.}$ is the total frequency Brick Star fires for household *j* in subpopulation *i* for the post KT phase.

*   $n^*_{ij}$ is the total number of days that household *j* in subpopulation *i* was observed in the post KT phase.

* $n^*_i$ is the number of households that were observed in the post KT phase.


***



The average Brick Star fuel use (in kg) in the project scenario for subpopulation *i* is calculated as the average of the household average fuel use per Brick Star fire.  $$\overline{x}_{(BS)i}=\frac{1}{n_{(P)i}}\sum_{j}^{n_{i}} \frac{x_{(BS)ij.}}{fr_{(BS)ij.}}$$

The total Brick Star fuel use for household *j* in subpopulation *i* is the total fuel use in the project scenario minus the fuel use by non-Brick Star fires in the project scenario.


$$x_{(BS)ij.}=x_{(P)ij.}-(\overline{x}_{(B)i} \times (fr_{(P)ij.}-fr_{(BS)ij.}))$$

***




### Calculation of baseline CO~2~ emissions

$BE_{y}$ is calculated as:

$$BE_{y} = \sum_{f} C_{(B)y,f} \times EF_{(CO_2)f} \times f_{(NRB)y}$$ 

Where:  

$C_{(B)y,f} =$ The total baseline consumption of fuel *f* for year *y* across all project participants (tonnes)  
$EF_{(CO_2)f} =$ CO~2~ emission factor for fuel *f*  
$f_{(NRB)y} =$ The fraction of non-renewable biomass in the fuel-sourcing environment for year *y* (as calculated in section \ref{sec:ifse})  

For simplicity in notation we will from this point forth use the notation $C_{(B)}$ for $C_{(B)y,f}$ with the understanding that $C_{(B)}$ is the total fuel consumption across all subpopulations and households for year *y* and fuel type *f*. 

$C_{(B)}$ is calculated as:


$$C_{(B)} = \sum_{i}^{n_i} eef_{i} \times C_{(P)i}$$

$C_{(P)i}$ is the total fuel consumption for subpopulations *i* (see calculation in previous paragraph).

$eef_i$ is the energy efficiency factor for subpopulation *i*.

$eef_i$ is calculated as

$$eef_i = \frac{\overline{x}_{(B)i}\times \overline{rr}_i}{\overline{x}_{(BS
)i}}$$

* $\overline{x}_{(B)i}$ is the average fuel use (in kg) in the baseline scenario for subpopulation *i*.
* $\overline{rr}_i$ is the average replacement ratio at which non-Brick Star fires are replaced by Brick Star fires for subpopulation *i*.
* $\overline{x}_{(BS)i}$ is the average Brick Star fuel use (in kg) in the baseline scenario for subpopulation *i*.

***
 
The average fuel use (in kg) in the baseline scenario for subpopulation *i* is calculated as the average fuel use (in kg) for the *j* households in subpopulation *i*.

$$\overline{x}_{(B)i}= \frac{1}{n_{ij}}\sum_{j} \overline{x}_{(B)ij}$$
and $\overline{x}_{(B)ij}$ is the average fuel use (in kg) in the baseline scenario for household *j* subpopulation *i*. $$\overline{x}_{(B)ij}=\frac{1}{n_{ijk}}\sum_{k}^{n_{ijk}} {x}_{(B)ijk}$$

***


The average replacement ratio is the average ratio for subpopulation *i* of the replaced non-Brick Star fires replaced by Brick Star fires and is calculated as

$$\overline{rr}_{i} = \frac{1}{n_{ij}}\sum_{j} rr_{ij}$$
and $rr_{ij}$ is the replacement ratio for household *j* in subpopulation *i*.
$$rr_{ij} = \frac{\overline{fr}_{(B)ij} - (\overline{fr}_{(P)ij}-\overline{fr}_{(BS)ij})}{\overline{fr}_{(BS)ij}}$$
$\overline{fr}_{(B)ij}$ is the average number of fires per day in the baseline scenario for household *j* in subpopulation *i* and is calculated as the total fires in the baseline scenario for household *j* in subpopulation *i* divided by the total days for household *j* in subpopulation *i* in the baseline scenario.
$$\overline{fr}_{(B)ij} = \frac{fr_{(B)ij.}}{{n_{(B)ij}}}$$
Similarly $\overline{fr}_{(P)}ij$ is the average number of fires per day in the project scenario for household *j* in subpopulation *i* $$\overline{fr}_{(P)ij} = \frac{fr_{(P)ij.}}{{n_{(P)ij}}}$$ and $\overline{fr}_{(BS)ij}$ is the average number of Brick Star fires per day in the project scenario for household *j* in subpopulation *i* $$\overline{fr}_{(BS)ij} = \frac{fr_{(BS)ij.}}{{n_{(BS)ij}}}$$ 

*** 



### Calculation of leakage CO~2~ emissions

Leakage will be due to continued use of baseline technology.
$LE_{y}$ is calculated as:

$$LE_{y} = \sum_{f} L_{(P)y,f} \times EF_{(CO_2)f} \times f_{(NRB)y}$$ 

Where:  

$L_{(P)y,f} =$ The total baseline consumption of fuel *f* for year *y* across all project participants (tonnes)  
$EF_{(CO_2)f} =$ CO~2~ emission factor for fuel *f*  
$f_{(NRB)y} =$ The fraction of non-renewable biomass in the fuel-sourcing environment for year *y* (as calculated in section \ref{sec:ifse})  

For simplicity in notation we will from this point forth use the notation $L_{(P)}$ for $L_{(P)y,f}
$ with the understanding that $L_{}$ is the total fuel consumption across all subpopulations and households for year *y* and fuel type *f*. 

$L_{(P)}$ is calculated as:


$$L_{(P)} = \sum_{i}^{n_i}  L_{(P)i}$$
and $L_{(P)i}$ is the total leakage in the project scenario for subpopulation *i*.
$L_{(P)i}$ is calculated as 

$$L_{(P)i}=(\overline{d}_{(P)i} \times N_{(P)i}) \times (
\overline{frr}_i\times \overline{fr^*}_{(BS)i} \times \overline{x}_{(B)i})$$

*   $\overline{d}_{(P)i}$ is the average days of project operation in subpopulation *i*.
*   $N_{(P)i}$ is the project population size in subpopulation *i*.
*   $\overline{frr}_i$ is the average frequency ratio of non Brick Star fires to the Brick Star fires in subpopulation *i* in the project scenario of the KT phase.
*   $\overline {fr^*}_{(BS)i}$ is the average Brick Star frequency per day in subpopulation *i* in the post KT phase .
*   $\overline{x}_{(B)i}$ is the average fuel use (in kg) for subpopulation *i* in the baseline scenario of the KT phase.

***

The average frequency ratio of non-Brick Star fires to the Brick Star fires in the project scenario for household *j* in subpopulation *i* is calculated as $$\overline{frr}_i = \frac {1}{n_{(P)i}} \sum_{j}\frac{fr_{(P)ij.}-fr_{(BS)ij.}}{fr_{(BS)ij.}}$$

***


### PM~10~ emission reduction due to project activity (t/yr)  

PM~10~ emissions are calculated in the same way as CO~2~ emissions with an appropriate PM~10~ emission factor for every fuel-device combination. 

### SO~2~ emission reduction due to project activity (t/yr)  

SO~2~ emissions are calculated in the same way as CO~2~ emissions with an appropriate SO~2~ emission factor for every fuel-device combination. 

### BC emission reduction due to project activity (t/yr)  

*Black Carbon* emissions are calculated in the same way as CO~2~ emissions with an appropriate BC emission factor for every fuel-device combination. 

## Indicators: indoor atmosphere  

The state of the *indoor atmosphere* will be expressed using the following indicators:

1.  99^th^ percentile CO hourly concentration in kitchen.
2.  99^th^ percentile PM~10~ daily concentration in kitchen.

### 99^th^ percentile CO hourly concentration in kitchen  

**Definition**  

The 99^th^ percentile value for hourly-averaged CO concentrations measured inside kitchens.  

**Rationale**  

CO bonds with haemoglobin, displacing oxygen and thus causing a lack of oxygen available for normal functioning of cells. 

**Source(s) of data** 

Measurements in a randomly selected sample of households.

**Credibility**  

*Avoidance of specification error*  
Use reputable measuring equipment.

*Avoidance of coverage or frame error*  
Document all participating households.  
Use a documented sampling strategy.

*Avoidance of non-response error*  
Consider moderate compensation to households for participation if tests are invasive.

*Avoidance of measurement error*  
Use reputable measuring equipment.

*Avoidance of processing errors*  
Make intermediate calculation steps transparent in reporting.

**Calculation**  

$$n = (99/100) \times N$$

Where:  

$N=$ The number of values in a observed data set  
$n=$ The ordinal rank of the 99^th^ percentile value  

The n^th^ value in the sorted observations (sorted from smallest to largest) is the 99^th^ percentile value.

**Unit of measure**  
hourly-averaged $\mu g.m^{-3}$

### 99^th^ percentile PM~10~ daily concentration in kitchen  

The 99^th^ percentile of the  daily concentration of PM~10~ in kitchens of participating households is calculated in the same way as the 99^th^ percentile value for hourly CO concentrations, with the exception that it is averaged to 24 hours. 








## Indicators: fuel-sourcing environment \label{sec:ifse}  

The state of the *fuel-sourcing environment* will be expressed using the following indicators:

1.  The fraction of non-renewable biomass in the fuel-sourcing environment.






### Fraction of non-renewable biomass

**Definition**  

The fraction of woody biomass that can be established as non-renewable biomass. 

**Rationale**  

Used in the calculation of greenhouse gas emission impact.

**Source(s) of data**  

Follow CDM Tool 30.

**Credibility**  

Follow requirements of CDM Tool 30. 


**Calculation**  

$$f_{NRB,y}=\frac{NRB_y}{NRB_y + RB_y}$$

Where:  

$f_{NRB,y}=$ Fraction of non-renewable biomass in the applicable area in year *y* (fraction or %) 

$NRB_y=$ Quantity of non-renewable biomass consumed in the applicable area in year *y*  (tonnes) 

$RB_y=$ Quantity of renewable biomass that is available on a sustainable basis in the applicable area in year *y* (tonnes) 

and $NRB_y$ is calculated as:

$$NRB_y = H_y - RB_y$$

Where:
$H_y=$ Total consumption of woody biomass in the applicable area in year *y* (tonnes) 

And $H_y$ is calculated as: 

$$H_y = HW_y \times N_y + CE_y + NE_y$$  

Where:  

$HW_y =$ Average extraction of wood fuel per household from the fuel-sourcing environment in year *y* (tonnes/household)  
$N_y =$ Number of households extracting wood fuel from the fuel-sourcing environment in year *y* (number)  
$CE_y =$ Commercial woody biomass extraction for energy applications (e.g. commercial, industrial or institutional uses of woody biomass in ovens, boilers etc.) from forests or other land areas in the fuel-sourcing environment in year *y* (tonnes)  
$NE_y =$ Commercial woody biomass extracted for non-energy applications (e.g. construction, furniture) from forests or other land areas in the fuel-sourcing environment in year *y* (tonnes)  


And $RB_y$ is calculated as:

$$RB_y = \sum (MIA_{forest,i,y} \times (F_{forest,i,y} - P_{forest,i,y})) + (MIA_{other,i,y} \times (F_{other,i,y} - P_{other,i,y})) $$


Where:  
$(MIA_{forest,i,y}=$ Mean Annual Increment in woody biomass per hectare in subcategory *i* of forest areas in year *y* (tonnes/ha/yr)  

$MIA_{other,i,y}$ Mean Annual Increment in woody biomass per hectare in sub-category *i* of other land areas in year *y* (tonnes/ha/yr)  

$F_{forest,i,y}$ Extent of forest in sub-category *i* in year *y* (ha)  

$F_{other,i,y}$ Extent of other land in sub-category *i* in year *y* (ha)  

$P_{forest,i,y}$ Extent of non-accessible area within forest areas (in sub-category *i*) in year *y* (ha)  

$P_{other,i,y}$ Extent of non-accessible area within other land areas (in sub-category *i*) in year *y* (ha)  

**Unit of measure**  
(fraction)








## Indicators: implementation settlement  

The state of the *implementation settlement* will be expressed using the following indicators: 

1.  Total annual fuelwood consumption per settlement.
2.  Similar projects in target area.






### Total annual fuelwood consumption per settlement  

**Definition**  

Annual mass of fuelwood used by all households within the implementation settlement (regardless of project participation or technology used).

**Rationale**  

Annual mass of fuelwood used by households within the target area is an indicator of the magnitude of the pressure on the wood resources in the environment as well as the maximum potential impact of the project. 

**Source(s) of data**  

*Geographic boundary of the target area for the project activity:*  
1. Specified as part of the project design.

*Population of the target area (i.e., number of households):*  
1. Official statistics.  
2. Remote sensing analysis.  
3. Census.  

*Average household wood use of project participants:*  
1. Project kitchen test.  
2. Project usage survey.  

*Average household wood use of non-project participants:*  
1. Baseline kitchen test.  
2. Baseline survey.  

<!--
**Credibility**  

*Avoidance of specification error*  
*Avoidance of coverage or frame error*   
*Avoidance of non-response error*   
*Avoidance of measurement error*  
*Avoidance of processing errors*  
-->

**Calculation**  

$$C_{s,y} = \sum_{i} \bar C_{i,y} \times N_{i,y}$$  

Where:  
$C_{s,y} =$ Total consumption of fuelwood during year *y* by settlement *s* (tonnes)  
$i =$ Index of fuel burning technologies present in settlement *s*    
$\bar C_{i,y} =$ Mean fuelwood consumption for technology *i* in year *y* (tonnes)  
$N_{i,y} =$ Number of users of technology *i* in settlement *s* during year *y*


**Unit of measure**  
tonnes per year (t/yr)







### Similar projects in target area

**Definition**  

List of activities similar to the project activity underway in the target area.

**Rationale**  

The baseline scenario is modified by the presence of similar activities.

**Source(s) of data**  

1. Registries of relevant standards bodies. 
2. Consultation with stakeholders. 

**Credibility**  
*Avoidance of specification error*  

Similar activities are fairly easy to identify by analysing the registries of relevant standards bodies ("relevant" means standards bodies with standards for activities similar in nature to that of the project activity). 

*Avoidance of coverage or frame error*  
There are a small number of registries. A well-planned public stakeholder consultation process would be highly likely to reveal the presence of similar activities. 

*Avoidance of non-response error*  
See above.

*Avoidance of measurement error*  
N/A.

*Avoidance of processing errors*  
N/A.

**Calculation**  
Incorporate the existence of similar activities in the description of the baseline scenario.

**Unit of measure**  
List.

<!-- Schema:Indicators schema:  Indicator ID, value, start period, end period-->
<!-- Indicator se pedegraa in VC of iets?-->

